services:
  - type: web
    name: expensetracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn expensetracker.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: expensetracker.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.1
